program: examples/wandb_gainakt2_train.py
method: bayes
metric:
  name: valid_auc
  goal: maximize
parameters:
  learning_rate:
    distribution: uniform
    min: 1e-5
    max: 1e-3
  dropout:
    distribution: uniform
    min: 0.1
    max: 0.4
  weight_decay:
    distribution: uniform
    min: 1e-6
    max: 1e-3
  num_encoder_blocks:
    values: [2, 3, 4]
  non_negative_loss_weight:
    distribution: uniform
    min: 0.0
    max: 0.2
  monotonicity_loss_weight:
    distribution: uniform
    min: 0.0
    max: 0.2
  mastery_performance_loss_weight:
    distribution: uniform
    min: 0.0
    max: 0.2
  gain_performance_loss_weight:
    distribution: uniform
    min: 0.0
    max: 0.2
  sparsity_loss_weight:
    distribution: uniform
    min: 0.0
    max: 0.2
